language: node_js
node_js:
  - "node"
services:
  - postgresql
before_script:
  - knex migrate:latest --env=test
  - knex seed:run --env=test
  - psql -c 'CREATE DATABASE all_palette_tests;' -U postgres